# timm model being used 
model_name: 'resnet101.a1_in1k'

# Directory where Tensorboard output goes 
log_dir: 'runs/resnet101/'

# Data related parameters 
data: 
  root: '/Users/hsantosv/Development/datasets/cheXpert/chexpert'
  batch_size: 16

# Optimization settings 
optimization: 
  num_epochs: 3
  learning_rate: 1e-4 