# timm model being used 
model_name: 'resnet101.a1_in1k'

# Directory where Tensorboard output goes 
log_dir: 'runs/resnet101/'

# Data related parameters 
data: 
  root: '/work/hdd/bfep/lewis1/chexpert'
  batch_size: 16
  num_workers: 4

# Optimization settings 
optimization: 
  num_epochs: 3
  learning_rate: 4e-4 